#ifndef __BSP_LED_CONF_H
#define __BSP_LED_CONF_H

#define BSP_LED_CONFIG_TOPIC "LED"
#define BSP_LED_COUNTUP_TOPIC "LED/COUNTUP"
#define BSP_LED_COUNTDOWN_TOPIC "LED/COUNTDOWN"

#define BSP_LED_DEFAULT_COUNT 5
#define BSP_LED_DEFAULT_PERIOD 5000
#define BSP_LED_DEFAULT_DUTY 200

#endif